spring:
  application:
    name: artmo

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 'update' 권장, 배포 시 'validate' 또는 'none'
    show-sql: true  # SQL 쿼리 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate 방언 설정
        format_sql: true  # Pretty-print SQL queries
        use_sql_comments: true  # Add comments to SQL queries

  devtools:
    livereload:
      enabled: true

storage:
  dir: storage
